"""fix user uniqueness

Revision ID: 0277fb020be9
Revises: a221165ce4e2
Create Date: 2026-05-13 18:27:45.512156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0277fb020be9'
down_revision: Union[str, Sequence[str], None] = 'a221165ce4e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    protocol_enum = postgresql.ENUM(
        'TCP', 'UDP', 'ICMP', 'OTHER',
        name='protocol'
    )
    protocol_enum.create(op.get_bind())

    op.alter_column(
        'matches',
        'protocol',
        type_=protocol_enum,
        postgresql_using='protocol::text::protocol'
    )

    op.alter_column(
        'network_logs',
        'protocol',
        type_=protocol_enum,
        existing_type=sa.VARCHAR(),
        existing_nullable=False,
        postgresql_using='protocol::text::protocol'
    )

    old_enum = postgresql.ENUM(name='protocolenum')
    old_enum.drop(op.get_bind(), checkfirst=True)

    sensor_enum = postgresql.ENUM(
        'online', 'offline', 'degraded',
        name='sensorstatus'
    )
    sensor_enum.create(op.get_bind())

    op.alter_column(
        'sensors',
        'status',
        type_=sensor_enum,
        existing_type=postgresql.ENUM(
            'online', 'offline', 'degraded',
            name='status'
        ),
        postgresql_using='status::text::sensorstatus'
    )

    op.create_unique_constraint(
        "uq_user_username",
        'user',
        ['username']
    )

    op.create_unique_constraint(
        "uq_user_email",
        'user',
        ['email']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint("uq_user_username", 'user', type_='unique')
    op.drop_constraint("uq_user_email", 'user', type_='unique')

    op.alter_column(
        'sensors',
        'status',
        existing_type=sa.Enum('online', 'offline', 'degraded', name='sensorstatus'),
        type_=postgresql.ENUM('online', 'offline', 'degraded', name='status'),
        existing_nullable=False,
        postgresql_using='status::text::status'
    )

    op.alter_column(
        'network_logs',
        'protocol',
        type_=sa.VARCHAR(),
        existing_type=sa.Enum('TCP', 'UDP', 'ICMP', 'OTHER', name='protocol'),
        existing_nullable=False,
        postgresql_using='protocol::text'
    )

    op.alter_column(
        'matches',
        'protocol',
        type_=postgresql.ENUM('TCP', 'UDP', 'ICMP', 'OTHER', name='protocolenum'),
        existing_type=sa.Enum('TCP', 'UDP', 'ICMP', 'OTHER', name='protocol'),
        postgresql_using='protocol::text::protocolenum'
    )

    postgresql.ENUM(name='protocol').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
