"""add missing rule-match relationship

Revision ID: 077841ce7106
Revises: fbf29ce222f4
Create Date: 2026-05-12 16:30:15.796759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '077841ce7106'
down_revision: Union[str, Sequence[str], None] = 'fbf29ce222f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('rule_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'matches', ['rule_id'])
    op.create_foreign_key(None, 'matches', 'rules', ['rule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_constraint(None, 'matches', type_='unique')
    op.drop_column('matches', 'rule_id')
    # ### end Alembic commands ###
