"""network log timestamp data type

Revision ID: 16df95e06781
Revises: 2cc2091482c1
Create Date: 2026-05-13 15:36:21.778479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16df95e06781'
down_revision: Union[str, Sequence[str], None] = '2cc2091482c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('network_logs', 'timestamp',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
                    postgresql_using="timestamp::timestamp")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('network_logs', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False,
                    postgresql_using="timestamp::varchar")
    # ### end Alembic commands ###
