"""fix alert created_at data type

Revision ID: 2cc2091482c1
Revises: 077841ce7106
Create Date: 2026-05-13 15:02:38.872720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cc2091482c1'
down_revision: Union[str, Sequence[str], None] = '077841ce7106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
            UPDATE alerts
            SET created_at = NOW()::text
            WHERE created_at !~ '^\\d{4}-\\d{2}-\\d{2}'
        """)
    op.alter_column('alerts', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
                    postgresql_using="created_at::timestamp")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.VARCHAR(),
               existing_nullable=False,
                    postgresql_using="created_at::text")
    # ### end Alembic commands ###
