"""add_rule_created_at_hit_count

Revision ID: ddfe7375dbba
Revises: 58d8f0e4a1b2
Create Date: 2026-05-23 18:57:06.671745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddfe7375dbba'
down_revision: Union[str, Sequence[str], None] = '58d8f0e4a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('rules', sa.Column('hit_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rules', 'hit_count')
    op.drop_column('rules', 'created_at')
    # ### end Alembic commands ###
