"""add missing rule matches

Revision ID: fbf29ce222f4
Revises: 9ae52dfc94bf
Create Date: 2026-05-12 16:25:09.953691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf29ce222f4'
down_revision: Union[str, Sequence[str], None] = '9ae52dfc94bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src_ip', sa.String(), nullable=True),
    sa.Column('dst_ip', sa.String(), nullable=True),
    sa.Column('dst_port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.Enum('TCP', 'UDP', 'ICMP', 'OTHER', name='protocolenum'), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=True),
    sa.Column('window_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matches')
    # ### end Alembic commands ###
